In [ ]:
import numpy as np


[[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]]


In [5]:

a = np.array([[1,2,3,4,5,6,7,8,9],[11,12,13,14,15,16,17,18,19]])
print(a)

[[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]]


In [ ]:
# get spicific rows and col 
a[1,8]


np.int64(19)

In [ ]:
# get spicific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# get spicific column
a[:,2]

array([ 3, 13])

In [ ]:
# getting a little more fancy [startIndex:endIndex:stepsize]
a[0,1:6:1]

a[1,8]=30
print(a)

[[ 1  2  3  4  5  6  7  8 30]
 [11 12 13 14 15 16 17 18 30]]


In [20]:
d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(d, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


In [44]:
a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20
print(b)

[ 1  2 20  4  5]


In [ ]:
# output = np.ones((7, 7))
# print(output)

output1 = np.zeros((7,7))
z = np.ones((5, 5))
z[2, 2] = 5

output1[1:-1, 1:-1] = z

In [48]:
a1 = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b1 = np.max(a1, axis=1).sum()
print(a1)
print(b1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
15
