# whats is Numpy ?
- Numpy is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. It is widely used in data science, machine learning, and scientific computing due to its efficiency and ease of use.
- Numpy stands for Numerical Python and is the fundamental package for numerical computations in Python.

# Key Features of Numpy
- **N-dimensional arrays**: Numpy provides a powerful N-dimensional array object, which is a fast and flexible container for large data sets in Python.
- **Mathematical functions**: It includes a wide range of mathematical functions to perform operations on arrays, such as linear algebra, statistical operations, and Fourier transforms.
- **Broadcasting**: Numpy supports broadcasting, which allows operations to be performed on arrays of different shapes and sizes without the need for explicit replication of data.
- **Performance**: Numpy is implemented in C, which makes it much faster than Python lists for numerical computations. It also supports vectorized operations, which can significantly speed up calculations.
- **Integration**: Numpy integrates well with other libraries in the Python ecosystem, such as Pandas, Matplotlib, and SciPy, making it a versatile tool for data analysis and scientific computing.

## what is difference between Numpy and Python List?
- **Data Type**: Numpy arrays are homogeneous, meaning all elements must be of the same data type, while Python lists can contain elements of different data types.
- **Performance**: Numpy arrays are more memory efficient and faster for numerical operations compared to Python lists, as they are implemented in C and optimized for performance.
- **Functionality**: Numpy provides a wide range of mathematical functions and operations that can be applied directly to arrays, while Python lists require manual iteration for similar operations.
- **Shape and Dimension**: Numpy arrays can have multiple dimensions (N-dimensional), while Python lists are one-dimensional by default, although they can be nested to create multi-dimensional structures.
- used the fixed type of data, while Python lists can store any type of object, including other lists, strings, and custom objects.

Basic Numpy Operations

In [ ]:
import numpy as np

In [ ]:
sizeone = np.array([1,2,3],dtype='int32')

print(sizeone)
sizeone.ndim
sizeone.shape
sizeone.dtype

[1 2 3]


dtype('int32')

In [16]:
sizetwo = np.array([[1,2,3],[4,5,6]])

print(sizetwo)
sizetwo.ndim
sizetwo.shape


[[1 2 3]
 [4 5 6]]


(2, 3)