In [ ]:
import numpy as np


[[ 29  97  32 100  45]
 [ 15  88   5  75  22]]


In [4]:

filedData = np.genfromtxt('../data/data.txt',delimiter=',')
filedData = filedData.astype('int32')

print(filedData)


[[ 29  97  32 100  45]
 [ 15  88   5  75  22]]


In [ ]:
output = np.any(filedData > 50)

print(output)


False


In [ ]:
filedata = np.genfromtxt('../data/data.txt',delimiter=',')

output = np.all(filedata < 50, axis=1)

print(output)


[False False]


In [16]:
output = filedata[filedata < 50]

print(output)

[29. 32. 45. 15.  5. 22.]
