In [ ]:
import numpy as np


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
a = np.ones((2, 4))
print(a)
b = a.reshape((4, 2))
print(b)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
a = np.ones((2, 4))
b = a.reshape((2, 4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
